version: '3'
services:
  redis-server:
    container_name: redis
    restart: on-failure
    image: 'redis'
    ports:
      - '6379:6379'
  mongo:
    container_name: mongo
    restart: on-failure
    image: mongo
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./logs:/var/log/mongodb/
      - ./db:/var/lib/mongodb
    ports:
      - '27017:27017'
  app:
    container_name: backend
    restart: always
    build: .
    ports:
      - '8080:3000'
    links:
      - mongo
      - redis-server
volumes:
  mongo-volume:
